name: Broken page
description: A page/blog post has a problem, and it’s not a regression from the previous website
title: 'Broken page: [Page title]'
labels: broken-page
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please note that this is **not** for reporting regressions from the previous website. For that, please use the [Page regression](/new?template=page-regression) template.
  - type: input
    id: url
    attributes:
      label: "Page URL:"
      description: URL of the page that is broken
      placeholder: ex. https://lea.verou.me/blog/2020/12/writable-getters/
    validations:
      required: true
  - type: dropdown
    id: issues
    attributes:
      label: What issues do you see?
      description: Please select all that apply
      multiple: true
      options:
        - Broken image(s)
        - Broken embed(s)
        - Figure caption not styled as a caption
        - Broken styles
        - Broken URLs
        - Broken syntax highlighting
        - Other
  - type: textarea
    id: details
    attributes:
      label: Description of issues
      description: Please provide more details
    validations:
      required: true



