name: Page regression
description: A page/blog post has a problem that it didn’t have on the previous website
title: 'Page regression: [Page title]'
labels: page-regression
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: url
    attributes:
      label: "Page URL:"
      description: URL of the page that is broken
      placeholder: ex. https://lea.verou.me/blog/2020/12/writable-getters/
    validations:
      required: true
  - type: checkboxes
    id: is_regression
    attributes:
      label: Does this problem exist in the previous site as well?
      description: If the issue is present in the previous site as well or not relevant to it, please file a [Broken Page](/new?template=broken-page) report instead.
      options:
        - label: I have verified that the issue is **not** present in the [previous site](https://lea0.verou.me).
          required: true
  - type: dropdown
    id: issues
    attributes:
      label: What issues do you see?
      description: Please select all that apply
      multiple: true
      options:
        - Broken image(s)
        - Broken embed(s)
        - Figure caption not styled as a caption
        - Broken styles
        - Broken URLs
        - Broken syntax highlighting
        - Other
  - type: textarea
    id: details
    attributes:
      label: Description of issues
      description: Please provide more details
    validations:
      required: true



